### ISSUE TITLE
ERBB2

### ISSUE THREAD

**Issue by jchodera** [choderalab/fah-projects#12]
Which X-ray crystal structures were used to set up the [ERBB2 project](https://github.com/choderalab/fah-projects/tree/master/projects/ERBB2_HUMAN_D0-10487)?

**Comment by kyleabeauchamp** [comment]
```
-bash-4.1$ cat initial-models/projects/ERBB2_HUMAN_D0/RUN*/template.txt 
ERBB2_HUMAN_D0_3PP0_A
ERBB2_HUMAN_D0_3RCD_A
```

**Comment by jchodera** [comment]
Perhaps my eyes are going, but where is the `initial-models` directory?

**Comment by kyleabeauchamp** [comment]
It's plfah1:/data/choderalab/fah/

We can't fit everything in github, so we decided on some things residing on the workserver.

**Comment by jchodera** [comment]
Got it.  Might make sense to check in initial models (or some metadata) if there's only a few modes used as templates.  Will add an issue about that which we can address later.  Thanks!
